
dbt_intro_da:
  target: dev_duckdb
  outputs:
    dev_duckdb:
      path: dbt.duckdb
      type: duckdb
    dev_bq:
      type: bigquery
      method: oauth
      project: formation-sql-316408
      dataset: dbt_intro_da_name
      location: EU
      threads: 4
