version: 2

sources:
  - name: dbt_intro
    tables:
      - name: ferrero_sales_per_week_dirty
      - name: crf_hyp_sales_fr_data
      - name: crf_sup_sales_fr_data
      - name: crf_prx_sales_fr_data
      - name: crf_sales_group_data
